<a href="https://colab.research.google.com/github/seifeldin36/fitness-center-system/blob/master/prem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/player_stats.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       568 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          568 non-null    float64
 5   born                         568 non-null    float64
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(3), int64(12), object(4)
memory usage: 84.9+ KB

In [ ]:
data.isna().sum()

name                           0
nation                         3
position                       0
team                           0
age                            3
born                           3
played                         0
starts                         0
minutes                        0
goals                          0
assists                        0
penalty_kicks                  0
penalty_kick_attempts          0
yellow                         0
red                            0
expected_goals                 0
progressive_carries            0
progressive_passes             0
received_progressive_passes    0
dtype: int64

In [ ]:
mask = data['nation'].isna()
data[mask]

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,NaN,FW,Leicester City,NaN,NaN,3,0,19,0,0,0,0,0,0,0.0,0,0,1
324,Mateus Mane,NaN,MF,Wolves,NaN,NaN,1,0,2,0,0,0,0,0,0,0.0,0,0,0
356,Jeremy Monga,NaN,"FW,MF",Leicester City,NaN,NaN,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
# Select rows where the name is 'Jake Evans' and fill the missing 'nation' values
data.loc[data['name'] == 'Jake Evans', 'nation'] = data.loc[data['name'] == 'Jake Evans', 'nation'].fillna('England')

In [ ]:
data.loc[data['name']== 'Mateus Mane','nation'] = data.loc[data['name']== 'Mateus Mane','nation'].fillna('Portugal')

In [ ]:
data.loc[data['name']=='Jeremy Monga','nation'] = data.loc[data['name']=='Jeremy Monga','nation'].fillna('England')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          568 non-null    float64
 5   born                         568 non-null    float64
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(3), int64(12), object(4)
memory usage: 84.9+ KB

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,England,FW,Leicester City,NaN,NaN,3,0,19,0,0,0,0,0,0,0.0,0,0,1
324,Mateus Mane,Portugal,MF,Wolves,NaN,NaN,1,0,2,0,0,0,0,0,0,0.0,0,0,0
356,Jeremy Monga,England,"FW,MF",Leicester City,NaN,NaN,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
mask_age = data['age'].isna()
data[mask_age]

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,England,FW,Leicester City,NaN,NaN,3,0,19,0,0,0,0,0,0,0.0,0,0,1
324,Mateus Mane,Portugal,MF,Wolves,NaN,NaN,1,0,2,0,0,0,0,0,0,0.0,0,0,0
356,Jeremy Monga,England,"FW,MF",Leicester City,NaN,NaN,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
# Select rows where the name is 'Jake Evans' and fill the missing 'nation' values
data.loc[data['name'] == 'Jake Evans', 'age'] = data.loc[data['name'] == 'Jake Evans', 'age'].fillna('17')
data.loc[data['name']== 'Mateus Mane','age'] = data.loc[data['name']== 'Mateus Mane','age'].fillna('17')
data.loc[data['name']=='Jeremy Monga','age'] = data.loc[data['name']=='Jeremy Monga','age'].fillna('16')

/tmp/ipython-input-3657065149.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['17']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data['name'] == 'Jake Evans', 'age'] = data.loc[data['name'] == 'Jake Evans', 'age'].fillna('17')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          571 non-null    object
 5   born                         568 non-null    float64
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(2), int64(12), object(5)
memory usage: 84.9+ KB

In [ ]:
# Select rows where the name is 'Jake Evans' and fill the missing 'nation' values
data.loc[data['name'] == 'Jake Evans', 'born'] = data.loc[data['name'] == 'Jake Evans', 'born'].fillna('2008')
data.loc[data['name']== 'Mateus Mane','born'] = data.loc[data['name']== 'Mateus Mane','born'].fillna('2008')
data.loc[data['name']=='Jeremy Monga','born'] = data.loc[data['name']=='Jeremy Monga','born'].fillna('2009')

/tmp/ipython-input-1020894060.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2008']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[data['name'] == 'Jake Evans', 'born'] = data.loc[data['name'] == 'Jake Evans', 'born'].fillna('2008')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          571 non-null    object
 5   born                         571 non-null    object
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(1), int64(12), object(6)
memory usage: 84.9+ KB

In [ ]:
data.head()

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
0,Max Aarons,England,DF,Bournemouth,25.0,2000.0,3,1,86,0,0,0,0,0,0,0.0,1,8,3
1,Joshua Acheampong,England,DF,Chelsea,19.0,2006.0,4,2,170,0,0,0,0,1,0,0.2,0,8,0
2,Tyler Adams,United States,MF,Bournemouth,26.0,1999.0,27,20,1875,0,3,0,0,7,0,1.6,13,71,10
3,Tosin Adarabioyo,England,DF,Chelsea,27.0,1997.0,21,14,1319,1,1,0,0,3,0,0.9,5,39,1
4,Simon Adingra,Cote dIvoire,"FW,MF",Brighton,23.0,2002.0,28,11,1052,2,2,0,0,0,0,2.4,50,18,128

In [ ]:
#Show how many goals for each team "descinding oreder"
data.groupby('team')['goals'].sum().sort_values(ascending=False)

team
Liverpool          84
Manchester City    69
Newcastle Utd      66
Arsenal            65
Brentford          64
Tottenham          60
Chelsea            60
Brighton           60
Nott'ham Forest    57
Aston Villa        56
Bournemouth        55
Fulham             53
Wolves             52
Crystal Palace     48
West Ham           40
Manchester Utd     40
Everton            38
Ipswich Town       34
Leicester City     33
Southampton        24
Name: goals, dtype: int64

In [ ]:
#Show The top 10 player scored goals
data.groupby('name')['goals'].sum().sort_values(ascending=False).head(10)

name
Mohamed Salah           28
Alexander Isak          23
Erling Haaland          21
Chris Wood              20
Yoane Wissa             19
Bryan Mbeumo            19
Ollie Watkins           16
Matheus Cunha           15
Cole Palmer             15
Jørgen Strand Larsen    14
Name: goals, dtype: int64

In [ ]:
#Show The top 10 players made assists
data.groupby('name')['assists'].sum().sort_values(ascending=False).head(10)

name
Mohamed Salah       18
Jacob Murphy        12
Anthony Elanga      11
Morgan Rogers       10
Antonee Robinson    10
Bukayo Saka         10
Mikkel Damsgaard    10
Son Heung-min        9
Bruno Fernandes      9
Ollie Watkins        8
Name: assists, dtype: int64

In [ ]:
#Show The top 10 players got red card
data.groupby('name')['red'].sum().sort_values(ascending=False).head(10)

name
Myles Lewis-Skelly    2
Bruno Fernandes       2
Jack Stephens         2
Lewis Cook            1
Declan Rice           1
Joachim Andersen      1
Morgan Gibbs-White    1
Rayan Aït-Nouri       1
Ashley Young          1
Mohammed Kudus        1
Name: red, dtype: int64

In [ ]:
#Show The top 10 scored by penalty
data.groupby('name')['penalty_kicks'].sum().sort_values(ascending=False).head(10)

name
Mohamed Salah      9
Justin Kluivert    6
João Pedro         5
Bryan Mbeumo       5
Cole Palmer        4
Alexander Isak     4
Raúl Jiménez       3
Chris Wood         3
Bruno Fernandes    3
Liam Delap         2
Name: penalty_kicks, dtype: int64

In [ ]:
#Show The top 10 players got red card
data.groupby('name')[['penalty_kick_attempts','penalty_kicks','team']].sum().sort_values(by= 'penalty_kick_attempts',ascending=False).head(10)

                 penalty_kick_attempts  penalty_kicks             team
name
Mohamed Salah                        9              9        Liverpool
Bryan Mbeumo                         6              5        Brentford
Justin Kluivert                      6              6      Bournemouth
Cole Palmer                          5              4          Chelsea
João Pedro                           5              5         Brighton
Alexander Isak                       4              4    Newcastle Utd
Raúl Jiménez                         3              3           Fulham
Bruno Fernandes                      3              3   Manchester Utd
Chris Wood                           3              3  Nott'ham Forest
Erling Haaland                       3              2  Manchester City

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          571 non-null    object
 5   born                         571 non-null    object
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(1), int64(12), object(6)
memory usage: 84.9+ KB

In [ ]:
data.groupby('name')[['minutes','position','team']].sum().sort_values(by= 'minutes',ascending=False).head(10)

                 minutes position             team
name
Bernd Leno          3330       GK           Fulham
Nathan Collins      3330       DF        Brentford
David Raya          3330       GK          Arsenal
Dean Henderson      3330       GK   Crystal Palace
Matz Sels           3330       GK  Nott'ham Forest
Jordan Pickford     3330       GK          Everton
Bryan Mbeumo        3324       FW        Brentford
Mohamed Salah       3281       FW        Liverpool
Moisés Caicedo      3261    MF,DF          Chelsea
Max Kilman          3258       DF         West Ham

In [ ]:
data.describe()

,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
count,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000,571.000000
mean,19.718039,14.255692,1280.558669,1.852890,1.378284,0.113835,0.138354,2.751313,0.087566,1.876532,24.288967,47.851138,47.357268
std,11.905889,12.026190,1028.756114,3.491755,2.227535,0.667018,0.720709,2.750020,0.300939,3.117080,31.782134,52.559513,65.892192
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,3.000000,319.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,2.000000,6.000000,2.000000
50%,21.000000,12.000000,1060.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.700000,12.000000,32.000000,18.000000
75%,31.000000,25.000000,2183.000000,2.000000,2.000000,0.000000,0.000000,4.000000,0.000000,2.100000,34.000000,71.000000,74.500000
max,37.000000,37.000000,3330.000000,28.000000,18.000000,9.000000,9.000000,12.000000,2.000000,24.800000,202.000000,302.000000,470.000000